WebApiDemo/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using WebApiDemo.Areas.HelpPage.ModelDescriptions;
using WebApiDemo.Areas.HelpPage.Models;

namespace WebApiDemo.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

WebApiDemo/Controllers/CRUDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApiDemo.DBEntity;
using System.Net.Http;

namespace WebApiDemo.Controllers
{
    public class CRUDController : Controller
    {
        // GET: CRUD
        public ActionResult Index()
        {
            IEnumerable<Employee> employeeData = null;
            HttpClient hc = new HttpClient
            {
                BaseAddress = new Uri("https://localhost:44310/api/Employee")
            };

            var consumeapi = hc.GetAsync("employee");
            consumeapi.Wait();

            var readdata = consumeapi.Result;
            if (readdata.IsSuccessStatusCode) {
                System.Threading.Tasks.Task<IList<Employee>> displaydata = readdata.Content.ReadAsAsync<IList<Employee>>();
                displaydata.Wait();
                employeeData = displaydata.Result;
            }
            return View(employeeData);
        }

        //Create: CRUD
        public ActionResult Create() {

            return View();
        }

        //Create: CRUD
        [HttpPost]
        public ActionResult Create(Employee InsEmployee)
        {
            HttpClient hc = new HttpClient
            {
                BaseAddress = new Uri("https://localhost:44310/api/employee")
            };
            System.Threading.Tasks.Task<HttpResponseMessage> InsertRecord = hc.PostAsJsonAsync<Employee>("Employee", InsEmployee);
            InsertRecord.Wait();

            var SaveData = InsertRecord.Result;

            if (SaveData.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View("Create");
        }

        // GET: CRUD
        public ActionResult Detail(int id)
        {
            Employee EmpObj = null;
            HttpClient hc = new HttpClient
            {
                BaseAddress = new Uri("https://localhost:44310/api/employee")
            };

            var consumeapi = hc.GetAsync("employee?id=" + id.ToString());
            consumeapi.Wait();

            var readdata = consumeapi.Result;
            if (readdata.IsSuccessStatusCode)
            {
                System.Threading.Tasks.Task<Employee> DisplayData = readdata.Content.ReadAsAsync<Employee>();

                DisplayData.Wait();
                EmpObj = DisplayData.Result;
            }
            return View(EmpObj);
        }

        public ActionResult Edit(int id)
        {
            Employee EmpObj = null;
            HttpClient hc = new HttpClient
            {
                BaseAddress = new Uri("https://localhost:44310/api/employee")
            };

            var consumeapi = hc.GetAsync("employee?id=" + id.ToString());
            consumeapi.Wait();

            var readdata = consumeapi.Result;
            if (readdata.IsSuccessStatusCode)
            {
                System.Threading.Tasks.Task<Employee> DisplayData = readdata.Content.ReadAsAsync<Employee>();

                DisplayData.Wait();
                EmpObj = DisplayData.Result;
            }
            return View(EmpObj);
        }

        [HttpPost]
        public ActionResult Edit(Employee em)
        {
            HttpClient hc = new HttpClient
            {
                BaseAddress = new Uri("https://localhost:44310/api/employee")
            };
            System.Threading.Tasks.Task<HttpResponseMessage> InsertRecord = hc.PutAsJsonAsync<Employee>("Employee", em);
            InsertRecord.Wait();

            var SaveData = InsertRecord.Result;

            if (SaveData.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.message("無可更新員工資料");
            }
            return View(em);

        }

        public ActionResult Delete(int id)
        {
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("https://localhost:44310/api/Employee");

            var delrecord = hc.DeleteAsync("Employee/" + id.ToString());
            delrecord.Wait();

            var displaydatee = delrecord.Result;
            if (displaydatee.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View("Index");
        }
    }
}

WebApiDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("應用程式名稱", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "CRUD", new { area = "" }, null)</li>
                    @*<li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CRUD範例</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>